#!/usr/bin/env bash
set -euo pipefail

echo "=== memory-code Mode vs Crosshash Feature Parity ==="
echo "Date: $(date -I)"
echo
echo "| # | memory-code mode | Crosshash equivalent | Parity |"
echo "|---|---|---|---|"
echo "| 1 | index-repo | crosshash index | FULL |"
echo "| 2 | reindex-repo | crosshash index --incremental | PARTIAL |"
echo "| 3 | call-hierarchy | graph callers | FULL |"
echo "| 4 | callees | graph callees | FULL |"
echo "| 5 | blast-radius | graph blast-radius | FULL |"
echo "| 6 | cycles | graph cycles | FULL |"
echo "| 7 | dead-code | — | NONE |"
echo "| 8 | complexity | — | NONE |"
echo "| 9 | import-graph | — | NONE |"
echo "| 10 | outline | — | NONE |"
echo "| 11 | churn | — | NONE |"
echo "| 12 | hotspots | — | NONE |"
echo "| 13 | importance | — | NONE |"
echo "| 14 | coupling | — | NONE |"
echo "| 15 | extractable | — | NONE |"
echo "| 16 | hierarchy | — | NONE |"
echo "| 17 | signal-chains | — | NONE |"
echo "| 18 | layer-violations | — | NONE |"
echo
echo "Crosshash unique capabilities (not in JS path):"
echo "  - Cross-repository impact analysis"
echo "  - AI-gated edge discovery with cost tracking"
echo "  - BLAKE3 content hashing for entity identity"
echo "  - Impact classification with SARIF output"
echo "  - MCP stdio server and HTTP API"
echo "  - File watching and live re-indexing"
echo "  - Entity versioning and diffing"
