const { withDb } = require('../../utils'),
  repos = require('./repos'),
  markdownParser = require('./markdown-parser'),
  htmlParser = require('./html-parser'),
  sections = require('./sections'),
  links = require('./links'),
  glossary = require('./glossary'),
  examples = require('./examples'),
  analytics = require('./analytics');

module.exports = {
  indexDocs: withDb(repos.indexDocs),
  reindexDocs: withDb(repos.reindexDocs),
  searchDocs: withDb(analytics.searchDocs),
  getDocOutline: withDb(sections.getDocOutline),
  getBacklinks: withDb(links.getBacklinks),
  getBrokenLinks: withDb(links.getBrokenLinks),
  lookupTerm: withDb(glossary.lookupTerm),
  getTutorialPath: withDb(analytics.getTutorialPath),
  findCodeExamples: withDb(examples.findCodeExamples),
  resolveLinks: withDb(links.resolveLinks),
  getOrphanSections: withDb(analytics.getOrphanSections),
  getDocCoverage: withDb(analytics.getDocCoverage),
  getStalePages: withDb(analytics.getStalePages),
  getDuplicateSections: withDb(analytics.getDuplicateSections),
  _parseMarkdownSections: markdownParser.parseMarkdownSections,
  _extractHtmlSections: htmlParser.extractHtmlSections,
  _extractHtmlLinks: htmlParser.extractHtmlLinks,
  _slugify: markdownParser.slugify,
  _extractLinks: links.extractLinks,
  _extractGlossaryTerms: glossary.extractGlossaryTerms,
  _extractCodeBlocks: examples.extractCodeBlocks,
  _getDocCoverageReport: analytics.getDocCoverageReport,
  _modules: { repos, markdownParser, htmlParser, sections, links, glossary, examples, analytics },
};
